---

- name: elasticsearch-configure | Set limits pt. 1
  lineinfile: dest=/etc/security/limits.conf regexp='^{{elasticsearch_user}}     -    nofile    {{elasticsearch_max_open_files}}' insertafter=EOF line='{{elasticsearch_user}}     -    nofile    {{elasticsearch_max_open_files}}'
  when: elasticsearch_max_open_files is defined
  sudo: true

- name: elasticsearch-configure | Set limits pt. 2
  lineinfile: dest=/etc/security/limits.conf regexp='^{{elasticsearch_user}}     -    memlock   {{elasticsearch_max_locked_memory}}' insertafter=EOF line='{{elasticsearch_user}}     -    memlock   {{elasticsearch_max_locked_memory}}'
  when: elasticsearch_max_locked_memory is defined
  sudo: true

