---

- name: elasticsearch-plugins | Plugin list
  debug: msg={{elasticsearch_plugins}}

- name: elasticsearch-plugins | Remove plugins
  command: "{{elasticsearch_home}}/bin/plugin --remove {{item.name}}"
  when: (item.remove is defined and item.remove) or (item.refresh)
  with_items: elasticsearch_plugins
  ignore_errors: yes
  sudo: yes
  sudo_user: "{{elasticsearch_user}}"
  notify:
    - restart elasticsearch

- name: elasticsearch-plugins | Install plugins
  command: "{{elasticsearch_home}}/bin/plugin --install {{item.name}} {%if item.url is defined %} --url {{item.url}}{% endif %} creates={{elasticsearch_plugindir}}/{{item.dir|default(item.name.split('/')[-1])}}"
  when: item.remove is not defined or not item.remove
  with_items: elasticsearch_plugins
  ignore_errors: yes
  sudo: yes
  sudo_user: "{{elasticsearch_user}}"
  notify: 
    - restart elasticsearch

